services:
  - type: web
    name: todo-backend-api
    env: node
    rootDir: todos-backend-master/todos-backend-master
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false  # Set this manually in Render dashboard for security